name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - uses: coursier/cache-action@v5
      - name: Install Scala Native dependencies
        run: sudo apt-get install libgc-dev libunwind8-dev
      - name: scalafmt
        run: ./scripts/scalafmt --test
      - name: Test
        run: sbt sbt-crossproject-test/scripted
